package com.myteam.colfax;

import org.apache.commons.lang.StringUtils;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ColfaxInfoArmorAttributes implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public ColfaxInfoArmorAttributes() {
	}

	private String effectiveDate;
	private String status;
	private String clientId;
	private String employeeId;
	private String memberFirstName;
	private String memberMiddleName;
	private String memberLastName;
	private String memberSSN;
	private String dobMonth;
	private String dobDay;
	private String dobYear;
	private String address1;
	private String address2;
	private String city;
	private String state;
	private Integer zipCode;
	private String areaCode;
	private String homePhone;
	private String email;
	private String deductionMethod;
	private String customerDefined;
	private String relationship;
	private String primary;
	private String familyId;
	private String uniqueId;
	private String planType;
	private String dateOfBirth;
	private String employeeAssignedID;
	private String benefitPlanTier;
	private String result;
	private String employerPaidPremium;
	private String coverageStatus;
	private String der_dependent_unique_id;

	public String getEffectiveDate() {
		return effectiveDate;
	}
	public void setEffectiveDate(String effectiveDate) {
		this.effectiveDate = effectiveDate;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getClientId() {
		return clientId;
	}
	public void setClientId(String clientId) {
		this.clientId = clientId;
	}
	public String getEmployeeId() {
		return employeeId;
	}
	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}
	public String getMemberFirstName() {
		return memberFirstName;
	}
	public void setMemberFirstName(String memberFirstName) {
		this.memberFirstName = memberFirstName;
	}
	public String getMemberMiddleName() {
		return memberMiddleName;
	}
	public void setMemberMiddleName(String memberMiddleName) {
		this.memberMiddleName = memberMiddleName;
	}
	public String getMemberLastName() {
		return memberLastName;
	}
	public void setMemberLastName(String memberLastName) {
		this.memberLastName = memberLastName;
	}
	public String getMemberSSN() {
		return memberSSN;
	}
	public void setMemberSSN(String memberSSN) {
		this.memberSSN = memberSSN;
	}
	public String getDobMonth() {
		return dobMonth;
	}
	public void setDobMonth(String dobMonth) {
		this.dobMonth = dobMonth;
	}
	public String getDobDay() {
		return dobDay;
	}
	public void setDobDay(String dobDay) {
		this.dobDay = dobDay;
	}
	public String getDobYear() {
		return dobYear;
	}
	public void setDobYear(String dobYear) {
		this.dobYear = dobYear;
	}
	public String getAddress1() {
		return address1;
	}
	public void setAddress1(String address1) {
		this.address1 = address1;
	}
	public String getAddress2() {
		return address2;
	}
	public void setAddress2(String address2) {
		this.address2 = address2;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public Integer getZipCode() {
		return zipCode;
	}
	public void setZipCode(Integer zipCode) {
		this.zipCode = zipCode;
	}
	public String getAreaCode() {
		return areaCode;
	}
	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}
	public String getHomePhone() {
		return homePhone;
	}
	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getDeductionMethod() {
		return deductionMethod;
	}
	public void setDeductionMethod(String deductionMethod) {
		this.deductionMethod = deductionMethod;
	}
	public String getCustomerDefined() {
		return customerDefined;
	}
	public void setCustomerDefined(String customerDefined) {
		this.customerDefined = customerDefined;
	}
	public String getRelationship() {
		return relationship;
	}
	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}
	public String getPrimary() {
		return primary;
	}
	public void setPrimary(String primary) {
		this.primary = primary;
	}
	public String getFamilyId() {
		return familyId;
	}
	public void setFamilyId(String familyId) {
		this.familyId = familyId;
	}
	public String getUniqueId() {
		return uniqueId;
	}
	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}
	public String getPlanType() {
		return planType;
	}
	public void setPlanType(String planType) {
		this.planType = planType;
	}
	public String getDateOfBirth() {
		return dateOfBirth;
	}
	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}
	public String getEmployeeAssignedID() {
		return employeeAssignedID;
	}
	public void setEmployeeAssignedID(String employeeAssignedID) {
		this.employeeAssignedID = employeeAssignedID;
	}
	public String getBenefitPlanTier() {
		return benefitPlanTier;
	}
	public void setBenefitPlanTier(String benefitPlanTier) {
		this.benefitPlanTier = benefitPlanTier;
	}
	public String getResult() {
		return this.result;
	}
	public void setResult(String result) {
		this.result = result;
	}
	public String getEmployerPaidPremium() {
		return employerPaidPremium;
	}
	public void setEmployerPaidPremium(String employerPaidPremium) {
		this.employerPaidPremium = employerPaidPremium;
	}
	public String getCoverageStatus() {
		return coverageStatus;
	}
	public void setCoverageStatus(String coverageStatus) {
		this.coverageStatus = coverageStatus;
	}
	
	public String getDer_dependent_unique_id() {
		return der_dependent_unique_id;
	}
	public void setDer_dependent_unique_id(String der_dependent_unique_id) {
		this.der_dependent_unique_id = der_dependent_unique_id;
	}
	
	public String getFamilyId(String employeeId) {
		String paddedStr = StringUtils.leftPad(employeeId, 8, "0");
		this.result = "E" + paddedStr;
		return this.result;
	}

	public String getDobSubString(String dob, int start, int end) {
		this.result = dob.substring(start, end).replaceFirst("^0+(?!$)", "");
		return this.result;
	}
}